### ISSUE TITLE
Skill erkennt keine Items

### ISSUE THREAD

**Issue by mryshakow** [Alpha200/snips-openhab#17]
Moin!

Der Skill erkennt bei mir keine Items und ich finde meinen Fehler nicht. Zwei Fehlerszenarien als Beispiel:

1. Ich sage "Mache das Licht im Wohnzimmer an", was auch verstanden wird. Der Skill antwortet mir mit "Ich habe kein Gerät gefunden, welches zu Deiner Anfrage passt".
2. Ich sage "Wie warm ist es im Schlafzimmer", was auch verstanden wird. Der Skill antwortet mir mit "Ich habe keinen Temperatursensor im Schlafzimmer gefunden".

Ich dachte erst, dass das Problem ist, dass es mehrere "Schlafzimmer" (Räume), bzw. mehrere "Lichter" (Setpoints) im Wohnzimmer gibt. Dann hätte der Skill aber anders antworten müssen: "Deine Anfrage war nicht eindeutig genug". Auch stutzig macht mich, dass im Log nichts vom erkannten Intend steht. Aber das müsste auch funktionieren, denn immerhin reagiert der Skill ja. Grobe Fehler in dem Items/Tagging habe ich auch ausgeschlossen, denn der HABot kann mit den Sätzen was anfangen und liefert mir entsprechende Ergebnisse, bzw. schaltet das Licht an/aus. Die Sprache von openHab ist Deutsch. Das Setup ist ein Server (Linux) und mehrere Satelliten (Linux, RP Zero). 

Anbei sind meine Items und zwei Logs der zwei Beispielsätze. Hast du eine Idee, wie ich mich dem Problem weiter nähern kann? Mache ich beim Tagging etwas falsch? Oder unterstützt der Skill nicht den Aufbau meiner Items (Raum in Raum in Raum..)?

Vielen Dank für deine Hilfe und viele Grüße
Michael

[all.items.txt](https://github.com/Alpha200/snips-openhab/files/3387759/all.items.txt)
[logsBeispiele.txt](https://github.com/Alpha200/snips-openhab/files/3387768/logsBeispiele.txt)

**Comment by Alpha200** [comment]
Hi, ich habe gerade ein großes Update auf den Master gepusht. Vielleicht funktioniert die App bei dir jetzt besser. Es gibt außerdem eine ausführlichere Dokumentation: https://snips-openhab.readthedocs.io/de/latest/basics/introduction.html

**Comment by mryshakow** [comment]
Ah super, vielen Dank für die Doku! Sobald der Skill wieder bei mir läuft, gebe ich hier nochmal Feedback.

**Comment by mryshakow** [comment]
Vermutlich hängt das Problem hier mit folgendem zusammen, daher schließe ich das hier mal mit Verweisauf: 
https://github.com/Alpha200/snips-openhab/issues/16
