### ISSUE TITLE
Write tests

### ISSUE THREAD

**Issue by Alpha200** [Alpha200/snips-openhab#19]
Mockups for the snips and OpenHAB API are needed for this.

**Comment by mryshakow** [comment]
Moin!

Wenn ok, würde ich mich erstmal um die openhab.py kümmern. Dafür würde ich [unittest](https://docs.python.org/3/library/unittest.html) bzw. [unittest.mock](https://docs.python.org/3/library/unittest.mock.html) verwenden. Hast du bestimmte Vorstellungen oder Wünsche? Sonst schau ich einfach mal wohin die Reise geht... :)

// Edit: Hab mitlerweile gesehen, dass du schon dran sitzt... 👍

**Comment by Alpha200** [comment]
Hi, hab vergessen dir zu schreiben. Wie du ja bereits gesehen hast, habe ich damit angefangen. Wenn du Lust hast kannst du gerne weitere Tests für die OpenHAB-Klasse schreiben und dann einen PR auf für den feature/tests-Branch erstellen.

Ich habe eine kleine Items-Datei zum Testen hinzugefügt und eine docker-compose-Konfiguration hinzugefügt womit man sich dann den Mock für die openHAB-Api erstellen kann. Falls du zum Testen noch weitere Items brauchst kannst du sie da einfach hinzufügen.

Ich will außerdem noch Tests für die action-openHAB.py schreiben, aber dazu werde ich das Projekt noch weiter refactoren.

Das Projekt ist jetzt auch mit Travis und Codecov verknüpft. Wenn du den PR stellen solltest werden die Tests dort automatisch ausgeführt.

**Comment by Alpha200** [comment]
Closed by #25
