### ISSUE TITLE
Restapi Warnings

### ISSUE THREAD

**Issue by xinQuon** [Alpha200/snips-openhab#2]
Hi Alpha,
bin neu hier. Finde es erst einmal super, dass du eine saubere Schnittstelle von Snips zu Openhab über eine SnipsApp entwickelst - fande bisher alle How-Tos etc. zur Anbindung von Openhab nicht befriedigend und suchte eine saubere Lösung, in welcher ich nicht zu viel Logig innerhalb von OH implementieren muss. Das Semantic Tagging über HABot finde ich hier einen guten Ansatz.
Zu meinem Problem:
- Habe nun testweise einige meiner Items getaggt und ich kann diese auch nun über Snips ansteuern. Dabei werden im OH Logging allerdings eine Menge Warnungen in dieser Form geworfen:
--> "[thome.io.rest.internal.DTOMapperImpl] - Field 'editable' could not be eliminated: Can not set boolean field..."

Nach ein paar Mal Licht an und Licht aus funktioniert deine App dann nicht mehr bzw. ich muss den Snips-Skill-Server restarten. 

Kannst du das bei dir reproduzieren?

Grüße aus Bremen

**Comment by Alpha200** [comment]
Hi xinQuon,
ich habe gerade das Problem mit den Warnings behoben. Es ist eigentlich ein Fehler in OpenHAB, der sich aber mit einem Workaround bei der Anfrage vermeiden lässt.

Dies sollte jedoch keinen Einfluss auf die Stabilität des Snips-Skills gehabt haben. Bei mir läuft die App stabil, ohne dass ich sie regelmäßig neu starten muss. Falls die App bei dir wieder hängen bleiben sollte, dann gucke Mal bitte bei dir in der Ausgabe von `sudo journalctl -u snips-skill-server.service` nach, ob meine App dort irgendwelche Fehlerausgaben erzeugt und wenn ja, dann schicke sie mir bitte.

**Comment by xinQuon** [comment]
Moin nochmal,
die Warnings sind weg aber nun reagiert die App leider gar nicht mehr. Habe mal im Log geschaut und da werden extrem viel Errors erzeugt (da es hier wohl eine Rekrusion ist und die Anzahl brutal, habe ich mal nur den Anfang und das Ende kopiert - alles dazwischen wiederholt sich wohl):

[openHAB][err] Traceback (most recent call last):
lib::runner: [openHAB][err]   File "_ctypes/callbacks.c", line 234, in 'calling callback function'
lib::runner: [openHAB][err]   File "/var/lib/snips/skills/snips-openhab/venv/lib/python3.5/site-packages/hermes_python/ffi/wrappers.py", line 61, in convert_arg
lib::runner: [openHAB][err]     return func(hermes_client, *parsed_args)
lib::runner: [openHAB][err]   File "./action-openHAB.py", line 119, in intent_callback
lib::runner: [openHAB][err]     relevant_devices = openhab.get_relevant_items(device, room)
lib::runner: [openHAB][err]   File "/var/lib/snips/skills/snips-openhab/openhab.py", line 113, in get_relevant_items
lib::runner: [openHAB][err]     items = [item for item in items if self.item_is_in_location(item, location)]
lib::runner: [openHAB][err]   File "/var/lib/snips/skills/snips-openhab/openhab.py", line 113, in <listcomp>
lib::runner: [openHAB][err]     items = [item for item in items if self.item_is_in_location(item, location)]
lib::runner: [openHAB][err]   File "/var/lib/snips/skills/snips-openhab/openhab.py", line 57, in item_is_in_location
lib::runner: [openHAB][err]     if self.group_is_location_in_location(group, location):
lib::runner: [openHAB][err]   File "/var/lib/snips/skills/snips-openhab/openhab.py", line 50, in group_is_location_in_location
lib::runner: [openHAB][err]     if self.group_is_location_in_location(parent, location):
lib::runner: [openHAB][err]   File "/var/lib/snips/skills/snips-openhab/openhab.py", line 50, in group_is_location_in_location
lib::runner: [openHAB][err]     if self.group_is_location_in_location(parent, location):
lib::runner: [openHAB][err]   File "/var/lib/snips/skills/snips-openhab/openhab.py", line 50, in group_is_location_in_location
lib::runner: [openHAB][err]     if self.group_is_location_in_location(parent, location):
lib::runner: [openHAB][err]   File "/var/lib/snips/skills/snips-openhab/openhab.py", line 50, in group_is_location_in_location
lib::runner: [openHAB][err]     if self.group_is_location_in_location(parent, location):
lib::runner: [openHAB][err]   File "/var/lib/snips/skills/snips-openhab/openhab.py", line 50, in group_is_location_in_location
lib::runner: [openHAB][err]     if self.group_is_location_in_location(parent, location):
lib::runner: [openHAB][err]   File "/var/lib/snips/skills/snips-openhab/openhab.py", line 50, in group_is_location_in_location
..................
..................
..................
lib::runner: [openHAB][err]     if self.group_is_location_in_location(parent, location):
lib::runner: [openHAB][err]   File "/var/lib/snips/skills/snips-openhab/openhab.py", line 50, in group_is_location_in_location
lib::runner: [openHAB][err]     if self.group_is_location_in_location(parent, location):
lib::runner: [openHAB][err]   File "/var/lib/snips/skills/snips-openhab/openhab.py", line 50, in group_is_location_in_location
lib::runner: [openHAB][err]     if self.group_is_location_in_location(parent, location):
lib::runner: [openHAB][err]   File "/var/lib/snips/skills/snips-openhab/openhab.py", line 43, in group_is_location_in_location
lib::runner: [openHAB][err]     if group == location.name:
lib::runner: [openHAB][err] RecursionError: maximum recursion depth exceeded in comparison

**Comment by Alpha200** [comment]
Kann es sein, dass es in deiner OpenHAB-Konfiguration einen Zykel bei der Verschachtelung der Gruppen gibt? Ich habe solch eine Situation bei Entwicklung nicht bedacht.

**Comment by xinQuon** [comment]
ja, war tatsächlich ein Zykel - mein Fehler. Hatte meine Gruppen neu gebaut und die Hauptlokation in sich selbst aufgenommen. Sorry. 

Kannst also das Thema auf gelöst setzen. Danke!
