### ISSUE TITLE
Item-Namen dynamisch zum Vokabular hinzufügen

### ISSUE THREAD

**Issue by Alpha200** [Alpha200/snips-openhab#3]
Über https://docs.snips.ai/articles/platform/nlu/dynamic-vocabulary kann das Vokabular des Assistenten erweitert werden. Über diesen Weg könnten Item-Namen, die nicht beim Training antrainiert wurden mit ins Vokabular aufgenommen werden.

**Comment by xinQuon** [comment]
Werde ich demnächst mal austesten.
Mal ne generelle Frage zum normalen Training:
- Ich verstehe es so, dass die Trainigsdaten ja quasi über die Definition der Intents und Tagging innerhalb der Sätze mit den entsprechenden Slots funktioniert. Ist es möglich, dass ich z.B. weitere Intents zu nicht von mir entwickelten Apps und damit die Qualität dieser erhöhe oder funktioniert so eine Erweiterung nur nur mit Fork der entsprechenden Apps?
