### ISSUE TITLE
Feedback zu Feature "dynamisches Vokabular bzw. Vokabular erweitern"

### ISSUE THREAD

**Issue by xinQuon** [Alpha200/snips-openhab#5]
Hi Alpha,
habe mich mal am Workaround versucht. Hatte die Frage ja auch schon im Snips Store (xion) gestellt: Musst du dazu noch deine App erweitern bzw. benötige ich ein Update meines Assistenten?

Habe testweise mal folgende json in die injection gejagt (Steuerung meines Ventilators über smarte Steckdose):

`{
    "operations": [
        [
            "add",
            {
                "device" : [
                    "Ventilator",
                    "Propeller"
                    "Windmaschiene"
                ]
            }
        ]
    ]
}
`

Gehe davon aus, dass dein Slot für devices "device" heißt und habe das entsprechend im json so eingebaut...Ist das semantisch so in Ordnung? Bisher funktionierts leider noch nicht :-(

**Comment by Alpha200** [comment]
Dieser Issue sollte sich durch die Implementierung von #3 erledigt haben.

**Comment by xinQuon** [comment]
Moin,
danke - werde hinterher mal testen. Ist meine Syntax oben denn richtig bzw. muss ich den Slot beim Add angeben?

Grüße aus Bremen

**Comment by xinQuon** [comment]
hat sich erledigt - funktioniert (wenn man an die Kommata denkt :-))
