### ISSUE TITLE
snips.toml wird nicht richtig ausgewertet 

### ISSUE THREAD

**Issue by happenpappen** [Alpha200/snips-openhab#6]
Wenn in der snips.toml ein anderer MQTT Server als localhost:1883 eingestellt wird,  wird diese Konfiguration ignoriert. Im systemd Journal kann man sehen, dass versucht wird sich weiterhin zu localhost:1883 zu verbinden.

**Comment by happenpappen** [comment]
> Wenn in der snips.toml ein anderer MQTT Server als localhost:1883 eingestellt wird, wird diese Konfiguration ignoriert. Im systemd Journal kann man sehen, dass versucht wird sich weiterhin zu localhost:1883 zu verbinden.

Noch ein paar Details dazu: Probiert habe ich das auf einem Raspberry Pi3 mit Raspbian Stretch und Snips Version 0.63.2. Ich konnte dieses Verhalten noch bei zwei anderen Skills ("Rechner+" von TMaddox und "Wikipedia" von Crystalmethod) beobachten, so dass das auch ein Problem der unterliegenden Python Bibliotheken sein könnte. Im Protokoll vom Skill Server sieht der Fehler so aus:

Jun 19 07:40:08 pi5 snips-skill-server[671]: INFO:snips_skill_server_lib::runner            : [openHAB][err] Traceback (most recent call last):
Jun 19 07:40:08 pi5 snips-skill-server[671]: INFO:snips_skill_server_lib::runner            : [openHAB][err]   File "./action-openHAB.py", line 250, in <module>
Jun 19 07:40:08 pi5 snips-skill-server[671]: INFO:snips_skill_server_lib::runner            : [openHAB][err]     with Hermes(mqtt_options=mqtt_opts) as h:
Jun 19 07:40:08 pi5 snips-skill-server[671]: INFO:snips_skill_server_lib::runner            : [openHAB][err]   File "/var/lib/snips/skills/snips-openhab/venv/lib/python3.5/
Jun 19 07:40:08 pi5 snips-skill-server[671]: INFO:snips_skill_server_lib::runner            : [openHAB][err]     return self.connect()
Jun 19 07:40:08 pi5 snips-skill-server[671]: INFO:snips_skill_server_lib::runner            : [openHAB][err]   File "/var/lib/snips/skills/snips-openhab/venv/lib/python3.5/
Jun 19 07:40:08 pi5 snips-skill-server[671]: INFO:snips_skill_server_lib::runner            : [openHAB][err]     self.ffi.establish_connection(self.mqtt_options)
Jun 19 07:40:08 pi5 snips-skill-server[671]: INFO:snips_skill_server_lib::runner            : [openHAB][err]   File "/var/lib/snips/skills/snips-openhab/venv/lib/python3.5/
Jun 19 07:40:08 pi5 snips-skill-server[671]: INFO:snips_skill_server_lib::runner            : [openHAB][err]     hermes_protocol_handler_new_mqtt_with_options(byref(self._p
Jun 19 07:40:08 pi5 snips-skill-server[671]: INFO:snips_skill_server_lib::runner            : [openHAB][err]   File "/var/lib/snips/skills/snips-openhab/venv/lib/python3.5/
Jun 19 07:40:08 pi5 snips-skill-server[671]: INFO:snips_skill_server_lib::runner            : [openHAB][err]     raise LibException(error_cause)
Jun 19 07:40:08 pi5 snips-skill-server[671]: INFO:snips_skill_server_lib::runner            : [openHAB][err] hermes_python.ffi.LibException: Could not create hermes MQTT ha
Jun 19 07:40:08 pi5 snips-skill-server[671]: INFO:snips_skill_server_lib::runner            : [openHAB][err]
Jun 19 07:40:08 pi5 snips-skill-server[671]: INFO:snips_skill_server_lib::runner            : [openHAB][err] Could not start MQTT client on localhost:1883
Jun 19 07:40:08 pi5 snips-skill-server[671]: INFO:snips_skill_server_lib::runner            : [openHAB][err]  -> caused by: Could not start MQTT client on localhost:1883
Jun 19 07:40:08 pi5 snips-skill-server[671]: INFO:snips_skill_server_lib::runner            : [openHAB][err]  -> caused by: Connection refused (os error 111)
Jun 19 07:40:08 pi5 snips-skill-server[671]: INFO:snips_skill_server_lib::runner            : [openHAB][err]
Jun 19 07:40:08 pi5 snips-skill-server[671]: WARN:snips_skill_server_lib::handler::nosandbox: child openHAB has stopped with status `exit code: 1`

**Comment by Alpha200** [comment]
Hi happenpappen, welcher Skill, der auch die Python Hermes-Bibliothek verwendet verbindet sich bei dir korrekt mit dem MQTT-Broker? Ich habe mich darauf verlassen, dass die Bibliothekt die Einstellungen selbst ausliest und dann verwendet. Wenn du mir einen Skill nennst, der funktioniert kann ich prüfen, was er anders macht und das in diesem Skill auch so implementieren.

**Comment by happenpappen** [comment]
Ich habe mal bei einem anderen Skill ("Snips-Wetter") geräubert und die folgenden Anpassungen an Deinem gemacht:

[snips-openhab-patch.txt](https://github.com/Alpha200/snips-openhab/files/3305496/snips-openhab-patch.txt)

Damit scheint der Fehler weg zu sein...

**Comment by Alpha200** [comment]
Danke für den Patch!
