### ISSUE TITLE
Temperatur auslesen

### ISSUE THREAD

**Issue by xinQuon** [Alpha200/snips-openhab#7]
Moin,
ich habe alles mögliche probiert aber deine App erkennt meinen Temperatursensor einfach nicht bzw. kann das Gerät trotz Tagging nicht finden - als letztes bin ich 1:1 wie bei deinem Beispielitem vorgegangen:

Number               nu_HueTemperatureSensor_Bad_Temperature    "Temperatur [%.1f °C]"           <temperature> (gr_loc_Badezimmer) ["Temperature", "Measurement"]    {channel=.......

Itent und Raum wird lt. sam watch sauber erkannt....

**Comment by polefski** [comment]
hast du die Gruppe gr_loc_Badezimmer den Raum ["Bathroom"] zugewiesen?
Es dürfen nur Location Namen verwendet werden, wie in dieser Beschreibung:

https://community.openhab.org/t/habot-walkthrough-2-n-semantic-tagging-item-resolving/55651

Wenn du eine Gruppe mit einem persönlichen Namen vergeben willst, musst du sie trotzdem z.b mit Bathroom taggen und kannst ein ein synonym für Snips hinzufügen wie du dann den Raum ansprechen willst.
Das heißt in deinem Fall sieht das z.B. so aus:

Group gr_loc_Badezimmer "Bad" <bath> (gOG)   ["Bathroom"] { synonyms="Bad, Badezimmer" }

**Comment by xinQuon** [comment]
Jo, hab ich...Lampen etc im Badezimmer lassen sich auch problemlos steuern ☹️ habe auch einen Hue Sensor in der Küche und gleiches Problem 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Alpha200** [comment]
Kannst du einmal nachprüfen, ob du in den Einstellungen von HABot die Attribute "messung" und "temperatur" bei deinem Item siehst?

**Comment by xinQuon** [comment]
Ja, aber in englisch 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by xinQuon** [comment]
![tempsensorhabot](https://user-images.githubusercontent.com/51043621/60202184-586c3880-984a-11e9-93fb-4ce8fdab64c0.PNG)

**Comment by Alpha200** [comment]
Ok, ich bin mir gerade nicht sicher, warum diese bei dir auf Englisch sind und bei mir auf deutsch. Der Skill funktioniert jedoch nur wenn die auf deutsch sind. Kannst du Mal in der PaperUI unter Preferences OpenHAB auf deutsch einstellen und OpenHAB dann neu starten? Vielleicht bringt das ja etwas.

**Comment by xinQuon** [comment]
Moin nochmal,
hat funktioniert und läuft nun - danke! Du kannst kannst ja noch einen Hinweis in dein Wiki einbauen :-)
Grüße aus Bremen

**Comment by Alpha200** [comment]
Alles klar, ist erledigt!
